"""
Order ID type classes for explicit distinction between internally-generated and exchange-assigned IDs.

This module provides type-safe wrappers for order identifiers to prevent confusion between:
- InternalOrderId: Internally-generated identifier (e.g., "B8688RteU9478d758")
- ExchangeOrderId: Exchange-assigned identifier (e.g., "201737149191")

Using distinct classes ensures ID type clarity at the code level, not just in comments.
"""

from dataclasses import dataclass
from typing import Union


@dataclass(frozen=True)
class InternalOrderId:
    """
    Internally-generated order identifier.

    This ID is generated by Helena Bot before submitting an order to the exchange.
    It's used to track orders throughout their lifecycle, even before the exchange
    assigns its own ID.

    Examples:
        - "B8688RteU9478d758"
        - "maker_order_20250115_123456"
        - "taker_order_20250115_123457"

    Attributes:
        value: The actual ID string
    """

    value: str

    def __str__(self) -> str:
        """Return the raw ID value for logging and string contexts."""
        return self.value

    def __repr__(self) -> str:
        """Return a debug representation showing the type."""
        return f"InternalOrderId({self.value})"

    def __hash__(self) -> int:
        """Support using as dictionary key."""
        return hash(self.value)


@dataclass(frozen=True)
class ExchangeOrderId:
    """
    Exchange-assigned order identifier.

    This ID is assigned by the exchange after successfully accepting an order.
    It's the canonical identifier used by the exchange for all order operations.

    Examples:
        - "201737149191" (Hyperliquid)
        - "12345678901234567890" (Binance)
        - "abc123-def456-ghi789" (other exchanges)

    Attributes:
        value: The actual ID string
    """

    value: str

    def __str__(self) -> str:
        """Return the raw ID value for logging and string contexts."""
        return self.value

    def __repr__(self) -> str:
        """Return a debug representation showing the type."""
        return f"ExchangeOrderId({self.value})"

    def __hash__(self) -> int:
        """Support using as dictionary key."""
        return hash(self.value)


@dataclass(frozen=True)
class RequestId:
    """
    Order request identifier - tracks order creation attempts.

    IMPORTANT: This is the CLIENT_ID assigned when creating an order request.
    It's the same value as InternalOrderId but used at the request tracking layer
    before the order is fully confirmed.

    The distinction exists because:
    - RequestId: Used in bot state management to track "request in progress"
    - InternalOrderId: Used in broker/gateway layer for actual order operations

    Examples:
        - "B8688RteU9478d758" (same format as InternalOrderId)

    Attributes:
        value: The actual ID string
    """

    value: str

    def __str__(self) -> str:
        """Return the raw ID value for logging and string contexts."""
        return self.value

    def __repr__(self) -> str:
        """Return a debug representation showing the type."""
        return f"RequestId({self.value})"

    def __hash__(self) -> int:
        """Support using as dictionary key."""
        return hash(self.value)

    def to_internal_order_id(self) -> "InternalOrderId":
        """
        Convert to InternalOrderId for broker/gateway operations.

        This conversion is explicit to make clear that we're transitioning
        from request tracking to order operation context.

        Returns:
            InternalOrderId with the same value
        """
        return InternalOrderId(self.value)


@dataclass(frozen=True)
class BlockClientId:
    """
    Block client identifier for reporting and metrics.

    This ID is different from RequestId - it's used for grouping trades
    into "blocks" for reporting purposes. Set by the routing engine to
    track related orders across a trading block.

    Examples:
        - Client IDs used for trade grouping/reporting

    Attributes:
        value: The actual ID string
    """

    value: str

    def __str__(self) -> str:
        """Return the raw ID value for logging and string contexts."""
        return self.value

    def __repr__(self) -> str:
        """Return a debug representation showing the type."""
        return f"BlockClientId({self.value})"

    def __hash__(self) -> int:
        """Support using as dictionary key."""
        return hash(self.value)


# Type alias for contexts where flexibility is needed
OrderIdentifier = Union[InternalOrderId, ExchangeOrderId]  # For maker_id/taker_id which can be either


# ============================================================================
# ID Type Conversion Helpers
# ============================================================================
# These helpers eliminate the need for isinstance checks throughout the codebase
# by providing centralized, type-safe conversion functions.
# ============================================================================


def ensure_internal_id(order_id: OrderIdentifier) -> InternalOrderId:
    """
    Convert OrderIdentifier to InternalOrderId.

    This helper eliminates the pattern:
        `order_id if isinstance(order_id, InternalOrderId) else InternalOrderId(str(order_id))`

    Args:
        order_id: Any order identifier type (InternalOrderId or ExchangeOrderId)

    Returns:
        InternalOrderId instance

    Example:
        >>> # Instead of: maker_id_client = maker_id if isinstance(maker_id, InternalOrderId) else InternalOrderId(str(maker_id))
        >>> maker_id_client = ensure_internal_id(maker_id)
    """
    if isinstance(order_id, InternalOrderId):
        return order_id
    # Convert from ExchangeOrderId or any other OrderIdentifier type
    return InternalOrderId(str(order_id))


__all__ = [
    "InternalOrderId",
    "ExchangeOrderId",
    "RequestId",
    "BlockClientId",
    "OrderIdentifier",
    "ensure_internal_id",
]
